stages:
  - tests
  - build
  - deploy
  
variables:
  BUILDVERSION: ${CI_PIPELINE_ID}

.test:
  image: rnds/ruby:3.0-test
  stage: tests
  variables:
    COMPOSE_PROJECT_NAME: bbkutils_${CI_PIPELINE_ID}_${CI_JOB_ID}
    GIT_BRANCH: ${CI_COMMIT_REF_NAME}
    GIT_COMMIT: ${CI_COMMIT_SHA}
  script:
    - docker-compose build --force-rm --pull test-${CASE}
    - docker-compose up --force-recreate -t 1 --remove-orphans -d test-${CASE}
    - docker-compose exec -T test-${CASE} rspec | tee .coverage
    - docker-compose exec -T test-${CASE} cat rspec.xml > rspec-${CASE}.xml
  after_script:
    - docker-compose down -v --remove-orphans
  coverage: '/\(\d+.\d+\%\) covered/'
  artifacts:
    reports:
      junit: rspec*.xml
    name: "coverage"
    paths:
      - .coverage
      - coverage

ruby-3.0:
  extends: .test
  variables:
    CASE: '3.0'
    RBS_TEST_TARGET: 'BBK::App::*'
    RBS_TEST_OPT: '-ruri -rbbk-utils -rlogger -rmonitor -I sig'
    RUBYOPT: '-rrbs/test/setup'
  
# steep:
#   image: rnds/ruby:3.0-test
#   stage: tests
#   variables:
#     CASE: '3.0'
#   script:
#     - docker-compose build --force-rm --pull test-${CASE}
#     - docker-compose up --force-recreate -t 1 --remove-orphans -d test-${CASE}
#     - docker-compose exec -T test-${CASE} steep check --with-expectations
#     - docker-compose exec -T test-${CASE} steep stats --format=table
#   after_script:
#     - docker-compose down -v --remove-orphans
  
build:
  image: rnds/ruby:3.0-test
  stage: build
  script:
    - bundle install --jobs=3 --path vendor/bundle && bundle package --all
    - gem build `ls | grep gemspec` # && gem install `ls | grep -e '.gem$'` 
  cache:
    paths:
      - vendor/bundle
      - vendor/cache
  artifacts:
    name: "gem"
    paths:
      - ./*.gem
      - coverage/*
      - rubycritic/*

.pushgem:
  image: rnds/ruby:3.0-test
  stage: deploy
  script:
    - mkdir -p ~/.gem
    - 'echo ":rubygems_api_key: ${RUBYGEMS_KEY}" > ~/.gem/credentials'
    - chmod 600 ~/.gem/credentials
    - export GEMFILE=`ls *.gem | tail -n 1`
    - gem push $GEMFILE

pushgem:
  extends: .pushgem
  only:
    - master
    - /^v\d$/
    - /^v\d\.\d$/

manual_push_gem:
  extends: .pushgem
  when: manual
  except:
    - master
    - /^v\d$/
    - /^v\d\.\d$/

