module BBK
  module App
    module Middlewares
      class SelfKiller

        attr_reader dispatcher: untyped
        attr_reader count: Integer
        attr_reader threshold: Integer
        attr_reader stop_time: Integer|Float

        def initialize: (untyped, ?delay: Integer, ?threshold: Integer, ?logger: _Logger) -> void
        def build: (untyped) -> void
        def call: (untyped) -> void  
          
        private

        def reset_log_time: () -> void
        def stop?: () -> void
        def threshold_exceed?: () -> bool
        def time_exceed?: (?Float) -> bool
        def close_dispatcher: () -> void

      end
    end
  end
end