require 'aggredator/client'

require 'aggredator/version'
require 'aggredator/executor'
require 'aggredator/factory'
require 'aggredator/matchers'
require 'aggredator/dispatcher'
require 'aggredator/processors'
require 'aggredator/watchdog'
require 'aggredator/handler'